spring:
  application:
    name: 'ecomplain'
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: "jdbc:postgresql://localhost:5432/ecomplain"
    username: 'postgres'
    password: 'postgres'
  jpa:
    hibernate:
      ddl-auto: 'update'
    properties:
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'